# Generated by Django 3.1.3 on 2020-11-29 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20201129_2119'),
        ('pages', '0002_post_summary'),
    ]

    operations = [
    ]
